In [1]:
import numpy as np

## Intro to Numpy

In [2]:
a = [1,2,3]

In [3]:
# To make a list np array
arr = np.array(a)
arr

array([1, 2, 3])

In [4]:
# To create array range
a_range = np.arange(1,10)
a_range

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# To create array range wit step
a_range_step = np.arange(1, 11, 2)
a_range_step

array([1, 3, 5, 7, 9])

In [6]:
# To create array of zeros
a_zeros = np.zeros(3)
a_zeros

array([0., 0., 0.])

In [7]:
# To create 2d array of zeros, pass tuple of dimensions
a_2d_zeros = np.zeros((3,4))
a_2d_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
# Same array can be created with ones
a_ones = np.ones(3)
a_ones

array([1., 1., 1.])

In [9]:
# To get 2d array of ones
a_2d_ones = np.ones((2,3))
a_2d_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
# To get a linearly spaced array, use linspace()
# It takes start number, end number and
# number of evenly spaced numbers between them
lin_space = np.linspace(0, 5, 5)
lin_space

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [11]:
# To get identity matrices, argument: size of matrix
ide_matrix = np.eye(4)
ide_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
# To get array of random numbers
rand_1d = np.random.rand(4)
rand_1d

array([0.94775092, 0.98638886, 0.37417123, 0.28389521])

In [13]:
# To get 2d array of random numbers, uses 2 arguments not tuple
rand_2d = np.random.rand(3, 4)
rand_2d

array([[0.99177566, 0.21589362, 0.71875204, 0.24691231],
       [0.14609775, 0.5283957 , 0.70832613, 0.98604468],
       [0.60752511, 0.59509366, 0.30673817, 0.57339762]])

In [14]:
# To get random numbers from standard normal distribution
randn_1d = np.random.randn(5)
randn_1d

array([ 0.54070114, -3.16326417,  0.80465252,  1.20841179, -0.62852226])

In [15]:
# To get random intergers, use randint()
# low number is inclusive, high number is exclusive
# size is size of array, can be 2d as tuple
rand_int = np.random.randint(1,10,3)
rand_int

array([8, 8, 6])

In [16]:
# use reshape method convert 1d array to 2d
arr = np.arange(25)
arr_2d = arr.reshape(5,5)
arr_2d
# reshape arguments contains size which should match the array
# or there will be an error

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
# To get max and min values out of array
rand_int = np.random.randint(1, 50, 10)
rand_int

array([46,  7, 26,  8, 21, 23,  8, 32, 11, 10])

In [18]:
# To get max value
max_val = rand_int.max()
max_val

46

In [19]:
# To get min value
min_val = rand_int.min()
min_val

7

In [20]:
# To index of max value
max_index = rand_int.argmax()
max_index

0

In [21]:
# To get index of min value
min_index = rand_int.argmin()
min_index

1

In [22]:
# To get shape of array, use shape attribute
# NOTE: shape is an attribute and not method so no '()' at the end
arr.shape

(25,)

In [23]:
# works with 2d array as well
arr_2d.shape

(5, 5)

In [24]:
# To know the data type of array, use dtype attribute(not a method)
arr.dtype

dtype('int64')

In [25]:
lin_space.dtype

dtype('float64')

## Numpy array indexing

In [26]:
# To view array
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr[5]

5

In [28]:
arr[3:5]

array([3, 4])

In [29]:
arr[:4]

array([0, 1, 2, 3])

In [30]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [31]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
# To slice an array
# NOTE: slicing does not create new array, it's just a view
slice_of_arr = arr[:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [33]:
# Broadcasting to change a value
# This will change all the values of slice_of_arr
slice_of_arr[:] = 100
slice_of_arr

array([100, 100, 100, 100, 100])

In [34]:
# Note that now, values of arr have also been changed
arr
# NOTE: numpy does this to save memory

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [35]:
# To avoid changing the initial value, copy the array
copy_of_arr = arr.copy()
copy_of_arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [36]:
# changing copy_of_arr
copy_of_arr[:5] = 99
copy_of_arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [37]:
# arr is still unchanged
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [38]:
# To get elements from 2d array
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [39]:
# Option 1, 2 bracket format
arr_2d[0][1]

10

In [40]:
# Option 2, single bracket format (preffered)
arr_2d[0,1]

10

In [41]:
# Passing just single param will result in array
arr_2d[0]

array([ 5, 10, 15])

In [42]:
# To grab section of array, use slicing
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

## Conditional selection

In [43]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
# Comparison operator will result in array of boolean
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [45]:
# for conditional selection, pass the bool array
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [46]:
# this is same as
arr[arr>5]

array([ 6,  7,  8,  9, 10])

## Numpy operations

In [47]:
# Arithmetic operations can be performed on array
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [49]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [50]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [51]:
# scalar operations can also be performed i.e. using single number
# For this numpy broadcasts that number and still the operation occurs
# number to number bases
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [52]:
arr / 10

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [53]:
# At time numpy will give warning instead of error
# below is not numpy and will give error
1/0

ZeroDivisionError: division by zero

In [ ]:
# but numpy will give only warning
arr / arr
# NOTE: since first element is 0, 0/0 should have been an error

In [ ]:
# again waring only here as well, 1/0 for first element
1 / arr

## Universal array function
Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array.

In [54]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [56]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [59]:
# this is same as arr.max()
np.max(arr)

10

In [61]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [63]:
np.log(arr)

<ipython-input-63-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

#### Check out the whole list of universal array functions [here]((http://docs.scipy.org/doc/numpy/reference/ufuncs.html))